myFiles = [ 
# 'root://eoscms//eos/cms/store/group/phys_tau/CMSSW_5_3_x/TauTriggerStudies/Ztautau_mc_v6/patTuple_10_1_AXC.root',
# 'root://eoscms//eos/cms/store/group/phys_tau/CMSSW_5_3_x/TauTriggerStudies/Ztautau_mc_v6/patTuple_11_1_a1D.root',
# 'root://eoscms//eos/cms/store/group/phys_tau/CMSSW_5_3_x/TauTriggerStudies/Ztautau_mc_v6/patTuple_12_1_8M5.root',
# 'root://eoscms//eos/cms/store/group/phys_tau/CMSSW_5_3_x/TauTriggerStudies/Ztautau_mc_v6/patTuple_13_1_JYi.root',
# 'root://eoscms//eos/cms/store/group/phys_tau/CMSSW_5_3_x/TauTriggerStudies/Ztautau_mc_v6/patTuple_14_1_7AN.root',
# 'root://eoscms//eos/cms/store/group/phys_tau/CMSSW_5_3_x/TauTriggerStudies/Ztautau_mc_v6/patTuple_15_1_y07.root',
# 'root://eoscms//eos/cms/store/group/phys_tau/CMSSW_5_3_x/TauTriggerStudies/Ztautau_mc_v6/patTuple_16_1_1TF.root',
# 'root://eoscms//eos/cms/store/group/phys_tau/CMSSW_5_3_x/TauTriggerStudies/Ztautau_mc_v6/patTuple_17_1_Noq.root',
# 'root://eoscms//eos/cms/store/group/phys_tau/CMSSW_5_3_x/TauTriggerStudies/Ztautau_mc_v6/patTuple_18_1_N3G.root',
# 'root://eoscms//eos/cms/store/group/phys_tau/CMSSW_5_3_x/TauTriggerStudies/Ztautau_mc_v6/patTuple_19_1_I3Z.root',
# 'root://eoscms//eos/cms/store/group/phys_tau/CMSSW_5_3_x/TauTriggerStudies/Ztautau_mc_v6/patTuple_1_1_lnT.root',
# 'root://eoscms//eos/cms/store/group/phys_tau/CMSSW_5_3_x/TauTriggerStudies/Ztautau_mc_v6/patTuple_20_1_3f6.root',
# 'root://eoscms//eos/cms/store/group/phys_tau/CMSSW_5_3_x/TauTriggerStudies/Ztautau_mc_v6/patTuple_2_1_x53.root',
# 'root://eoscms//eos/cms/store/group/phys_tau/CMSSW_5_3_x/TauTriggerStudies/Ztautau_mc_v6/patTuple_3_1_raU.root',
# 'root://eoscms//eos/cms/store/group/phys_tau/CMSSW_5_3_x/TauTriggerStudies/Ztautau_mc_v6/patTuple_4_1_TfY.root',
# 'root://eoscms//eos/cms/store/group/phys_tau/CMSSW_5_3_x/TauTriggerStudies/Ztautau_mc_v6/patTuple_5_1_wsE.root',
# 'root://eoscms//eos/cms/store/group/phys_tau/CMSSW_5_3_x/TauTriggerStudies/Ztautau_mc_v6/patTuple_6_1_yyo.root',
# 'root://eoscms//eos/cms/store/group/phys_tau/CMSSW_5_3_x/TauTriggerStudies/Ztautau_mc_v6/patTuple_7_1_D1e.root',
# 'root://eoscms//eos/cms/store/group/phys_tau/CMSSW_5_3_x/TauTriggerStudies/Ztautau_mc_v6/patTuple_8_1_lXv.root',
# 'root://eoscms//eos/cms/store/group/phys_tau/CMSSW_5_3_x/TauTriggerStudies/Ztautau_mc_v6/patTuple_9_1_Pzh.root',
# 
# 
# 'root://eoscms//eos/cms/store/group/phys_tau/CMSSW_5_3_x/TauTriggerStudies/Ztautau_mc_v5/patTuple_1_1_eLb.root',
# 'root://eoscms//eos/cms/store/group/phys_tau/CMSSW_5_3_x/TauTriggerStudies/Ztautau_mc_v5/patTuple_2_1_6w7.root',
# 'root://eoscms//eos/cms/store/group/phys_tau/CMSSW_5_3_x/TauTriggerStudies/Ztautau_mc_v5/patTuple_3_1_nNG.root',
# 'root://eoscms//eos/cms/store/group/phys_tau/CMSSW_5_3_x/TauTriggerStudies/Ztautau_mc_v5/patTuple_4_1_AEP.root',


            'root://eoscms//eos/cms/store/group/phys_tau/CMSSW_5_3_x/TauTriggerStudies/Ztautau_mc_v4/patTuple_10_1_JX2.root',
            'root://eoscms//eos/cms/store/group/phys_tau/CMSSW_5_3_x/TauTriggerStudies/Ztautau_mc_v4/patTuple_11_1_N2T.root',
            'root://eoscms//eos/cms/store/group/phys_tau/CMSSW_5_3_x/TauTriggerStudies/Ztautau_mc_v4/patTuple_12_1_Zx5.root',
            'root://eoscms//eos/cms/store/group/phys_tau/CMSSW_5_3_x/TauTriggerStudies/Ztautau_mc_v4/patTuple_13_1_aBL.root',
            'root://eoscms//eos/cms/store/group/phys_tau/CMSSW_5_3_x/TauTriggerStudies/Ztautau_mc_v4/patTuple_14_1_1jN.root',
            'root://eoscms//eos/cms/store/group/phys_tau/CMSSW_5_3_x/TauTriggerStudies/Ztautau_mc_v4/patTuple_15_1_oax.root',
            'root://eoscms//eos/cms/store/group/phys_tau/CMSSW_5_3_x/TauTriggerStudies/Ztautau_mc_v4/patTuple_16_1_OJ5.root',
            'root://eoscms//eos/cms/store/group/phys_tau/CMSSW_5_3_x/TauTriggerStudies/Ztautau_mc_v4/patTuple_17_1_Yrp.root',
            'root://eoscms//eos/cms/store/group/phys_tau/CMSSW_5_3_x/TauTriggerStudies/Ztautau_mc_v4/patTuple_18_1_Oyd.root',
            'root://eoscms//eos/cms/store/group/phys_tau/CMSSW_5_3_x/TauTriggerStudies/Ztautau_mc_v4/patTuple_19_1_KCn.root',
            'root://eoscms//eos/cms/store/group/phys_tau/CMSSW_5_3_x/TauTriggerStudies/Ztautau_mc_v4/patTuple_1_1_ios.root',
            'root://eoscms//eos/cms/store/group/phys_tau/CMSSW_5_3_x/TauTriggerStudies/Ztautau_mc_v4/patTuple_20_1_i1j.root',
            'root://eoscms//eos/cms/store/group/phys_tau/CMSSW_5_3_x/TauTriggerStudies/Ztautau_mc_v4/patTuple_2_1_X3i.root',
            'root://eoscms//eos/cms/store/group/phys_tau/CMSSW_5_3_x/TauTriggerStudies/Ztautau_mc_v4/patTuple_3_1_In7.root',
            'root://eoscms//eos/cms/store/group/phys_tau/CMSSW_5_3_x/TauTriggerStudies/Ztautau_mc_v4/patTuple_4_1_zCP.root',
            'root://eoscms//eos/cms/store/group/phys_tau/CMSSW_5_3_x/TauTriggerStudies/Ztautau_mc_v4/patTuple_5_1_1Q8.root',
            'root://eoscms//eos/cms/store/group/phys_tau/CMSSW_5_3_x/TauTriggerStudies/Ztautau_mc_v4/patTuple_6_1_wmE.root',
            'root://eoscms//eos/cms/store/group/phys_tau/CMSSW_5_3_x/TauTriggerStudies/Ztautau_mc_v4/patTuple_7_1_wA8.root',
            'root://eoscms//eos/cms/store/group/phys_tau/CMSSW_5_3_x/TauTriggerStudies/Ztautau_mc_v4/patTuple_8_1_PJ4.root',
            'root://eoscms//eos/cms/store/group/phys_tau/CMSSW_5_3_x/TauTriggerStudies/Ztautau_mc_v4/patTuple_9_1_sCt.root',


            'root://eoscms//eos/cms/store/group/phys_tau/CMSSW_5_3_x/TauTriggerStudies/Zprime_mc_v3/patTuple_10_1_1ZT.root',
            'root://eoscms//eos/cms/store/group/phys_tau/CMSSW_5_3_x/TauTriggerStudies/Zprime_mc_v3/patTuple_11_1_v1d.root',
            'root://eoscms//eos/cms/store/group/phys_tau/CMSSW_5_3_x/TauTriggerStudies/Zprime_mc_v3/patTuple_12_1_Di7.root',
            'root://eoscms//eos/cms/store/group/phys_tau/CMSSW_5_3_x/TauTriggerStudies/Zprime_mc_v3/patTuple_13_1_3ea.root',
            'root://eoscms//eos/cms/store/group/phys_tau/CMSSW_5_3_x/TauTriggerStudies/Zprime_mc_v3/patTuple_14_1_kj0.root',
            'root://eoscms//eos/cms/store/group/phys_tau/CMSSW_5_3_x/TauTriggerStudies/Zprime_mc_v3/patTuple_15_1_ngP.root',
            'root://eoscms//eos/cms/store/group/phys_tau/CMSSW_5_3_x/TauTriggerStudies/Zprime_mc_v3/patTuple_16_1_GfS.root',
            'root://eoscms//eos/cms/store/group/phys_tau/CMSSW_5_3_x/TauTriggerStudies/Zprime_mc_v3/patTuple_17_1_iuq.root',
            'root://eoscms//eos/cms/store/group/phys_tau/CMSSW_5_3_x/TauTriggerStudies/Zprime_mc_v3/patTuple_18_1_KzQ.root',
            'root://eoscms//eos/cms/store/group/phys_tau/CMSSW_5_3_x/TauTriggerStudies/Zprime_mc_v3/patTuple_19_1_rNm.root',
            'root://eoscms//eos/cms/store/group/phys_tau/CMSSW_5_3_x/TauTriggerStudies/Zprime_mc_v3/patTuple_1_1_5PH.root',
            'root://eoscms//eos/cms/store/group/phys_tau/CMSSW_5_3_x/TauTriggerStudies/Zprime_mc_v3/patTuple_20_1_beV.root',
            'root://eoscms//eos/cms/store/group/phys_tau/CMSSW_5_3_x/TauTriggerStudies/Zprime_mc_v3/patTuple_21_1_Nmv.root',
            'root://eoscms//eos/cms/store/group/phys_tau/CMSSW_5_3_x/TauTriggerStudies/Zprime_mc_v3/patTuple_22_1_Z3i.root',
            'root://eoscms//eos/cms/store/group/phys_tau/CMSSW_5_3_x/TauTriggerStudies/Zprime_mc_v3/patTuple_23_1_gVl.root',
            'root://eoscms//eos/cms/store/group/phys_tau/CMSSW_5_3_x/TauTriggerStudies/Zprime_mc_v3/patTuple_24_1_Hqw.root',
            'root://eoscms//eos/cms/store/group/phys_tau/CMSSW_5_3_x/TauTriggerStudies/Zprime_mc_v3/patTuple_25_1_7eQ.root',
            'root://eoscms//eos/cms/store/group/phys_tau/CMSSW_5_3_x/TauTriggerStudies/Zprime_mc_v3/patTuple_26_1_Anl.root',
            'root://eoscms//eos/cms/store/group/phys_tau/CMSSW_5_3_x/TauTriggerStudies/Zprime_mc_v3/patTuple_2_1_w6W.root',
            'root://eoscms//eos/cms/store/group/phys_tau/CMSSW_5_3_x/TauTriggerStudies/Zprime_mc_v3/patTuple_3_1_UGL.root',
            'root://eoscms//eos/cms/store/group/phys_tau/CMSSW_5_3_x/TauTriggerStudies/Zprime_mc_v3/patTuple_4_1_JMS.root',
            'root://eoscms//eos/cms/store/group/phys_tau/CMSSW_5_3_x/TauTriggerStudies/Zprime_mc_v3/patTuple_5_1_xvX.root',
            'root://eoscms//eos/cms/store/group/phys_tau/CMSSW_5_3_x/TauTriggerStudies/Zprime_mc_v3/patTuple_6_1_Eb2.root',
            'root://eoscms//eos/cms/store/group/phys_tau/CMSSW_5_3_x/TauTriggerStudies/Zprime_mc_v3/patTuple_7_1_dmb.root',
            'root://eoscms//eos/cms/store/group/phys_tau/CMSSW_5_3_x/TauTriggerStudies/Zprime_mc_v3/patTuple_8_1_9jv.root',
            'root://eoscms//eos/cms/store/group/phys_tau/CMSSW_5_3_x/TauTriggerStudies/Zprime_mc_v3/patTuple_9_1_svY.root',
    
]        
            