myFiles = [ 
'root://eoscms//eos/cms/store/cmst3/user/manzoni/TauPOG/11feb/ZTauTau_first4PixelVtx_sorted4power/patTuple_10_1_VXl.root',
'root://eoscms//eos/cms/store/cmst3/user/manzoni/TauPOG/11feb/ZTauTau_first4PixelVtx_sorted4power/patTuple_11_1_YPV.root',
'root://eoscms//eos/cms/store/cmst3/user/manzoni/TauPOG/11feb/ZTauTau_first4PixelVtx_sorted4power/patTuple_12_1_zN9.root',
'root://eoscms//eos/cms/store/cmst3/user/manzoni/TauPOG/11feb/ZTauTau_first4PixelVtx_sorted4power/patTuple_13_1_PIu.root',
'root://eoscms//eos/cms/store/cmst3/user/manzoni/TauPOG/11feb/ZTauTau_first4PixelVtx_sorted4power/patTuple_14_1_L9f.root',
'root://eoscms//eos/cms/store/cmst3/user/manzoni/TauPOG/11feb/ZTauTau_first4PixelVtx_sorted4power/patTuple_15_1_3GA.root',
'root://eoscms//eos/cms/store/cmst3/user/manzoni/TauPOG/11feb/ZTauTau_first4PixelVtx_sorted4power/patTuple_16_1_zSJ.root',
'root://eoscms//eos/cms/store/cmst3/user/manzoni/TauPOG/11feb/ZTauTau_first4PixelVtx_sorted4power/patTuple_17_1_BUz.root',
'root://eoscms//eos/cms/store/cmst3/user/manzoni/TauPOG/11feb/ZTauTau_first4PixelVtx_sorted4power/patTuple_18_1_2BA.root',
'root://eoscms//eos/cms/store/cmst3/user/manzoni/TauPOG/11feb/ZTauTau_first4PixelVtx_sorted4power/patTuple_19_1_788.root',
'root://eoscms//eos/cms/store/cmst3/user/manzoni/TauPOG/11feb/ZTauTau_first4PixelVtx_sorted4power/patTuple_1_1_eeX.root',
'root://eoscms//eos/cms/store/cmst3/user/manzoni/TauPOG/11feb/ZTauTau_first4PixelVtx_sorted4power/patTuple_20_1_KR0.root',
'root://eoscms//eos/cms/store/cmst3/user/manzoni/TauPOG/11feb/ZTauTau_first4PixelVtx_sorted4power/patTuple_2_1_LsX.root',
'root://eoscms//eos/cms/store/cmst3/user/manzoni/TauPOG/11feb/ZTauTau_first4PixelVtx_sorted4power/patTuple_3_1_xMx.root',
'root://eoscms//eos/cms/store/cmst3/user/manzoni/TauPOG/11feb/ZTauTau_first4PixelVtx_sorted4power/patTuple_4_1_jou.root',
'root://eoscms//eos/cms/store/cmst3/user/manzoni/TauPOG/11feb/ZTauTau_first4PixelVtx_sorted4power/patTuple_5_1_xhE.root',
'root://eoscms//eos/cms/store/cmst3/user/manzoni/TauPOG/11feb/ZTauTau_first4PixelVtx_sorted4power/patTuple_6_1_AIB.root',
'root://eoscms//eos/cms/store/cmst3/user/manzoni/TauPOG/11feb/ZTauTau_first4PixelVtx_sorted4power/patTuple_7_1_fLA.root',
'root://eoscms//eos/cms/store/cmst3/user/manzoni/TauPOG/11feb/ZTauTau_first4PixelVtx_sorted4power/patTuple_8_1_ehq.root',
'root://eoscms//eos/cms/store/cmst3/user/manzoni/TauPOG/11feb/ZTauTau_first4PixelVtx_sorted4power/patTuple_9_1_UZ5.root',
'root://eoscms//eos/cms/store/cmst3/user/manzoni/TauPOG/11feb/ZPrimeTauTau_first4PixelVtx_sorted4power/patTuple_10_1_1KW.root',
'root://eoscms//eos/cms/store/cmst3/user/manzoni/TauPOG/11feb/ZPrimeTauTau_first4PixelVtx_sorted4power/patTuple_11_1_RmM.root',
'root://eoscms//eos/cms/store/cmst3/user/manzoni/TauPOG/11feb/ZPrimeTauTau_first4PixelVtx_sorted4power/patTuple_12_1_SWn.root',
'root://eoscms//eos/cms/store/cmst3/user/manzoni/TauPOG/11feb/ZPrimeTauTau_first4PixelVtx_sorted4power/patTuple_13_1_z1U.root',
'root://eoscms//eos/cms/store/cmst3/user/manzoni/TauPOG/11feb/ZPrimeTauTau_first4PixelVtx_sorted4power/patTuple_14_1_55P.root',
'root://eoscms//eos/cms/store/cmst3/user/manzoni/TauPOG/11feb/ZPrimeTauTau_first4PixelVtx_sorted4power/patTuple_15_1_4eU.root',
'root://eoscms//eos/cms/store/cmst3/user/manzoni/TauPOG/11feb/ZPrimeTauTau_first4PixelVtx_sorted4power/patTuple_16_1_4YD.root',
'root://eoscms//eos/cms/store/cmst3/user/manzoni/TauPOG/11feb/ZPrimeTauTau_first4PixelVtx_sorted4power/patTuple_17_1_AF0.root',
'root://eoscms//eos/cms/store/cmst3/user/manzoni/TauPOG/11feb/ZPrimeTauTau_first4PixelVtx_sorted4power/patTuple_18_1_0Ro.root',
'root://eoscms//eos/cms/store/cmst3/user/manzoni/TauPOG/11feb/ZPrimeTauTau_first4PixelVtx_sorted4power/patTuple_1_1_Zx4.root',
'root://eoscms//eos/cms/store/cmst3/user/manzoni/TauPOG/11feb/ZPrimeTauTau_first4PixelVtx_sorted4power/patTuple_2_1_0L1.root',
'root://eoscms//eos/cms/store/cmst3/user/manzoni/TauPOG/11feb/ZPrimeTauTau_first4PixelVtx_sorted4power/patTuple_3_1_c9d.root',
'root://eoscms//eos/cms/store/cmst3/user/manzoni/TauPOG/11feb/ZPrimeTauTau_first4PixelVtx_sorted4power/patTuple_4_1_pg6.root',
'root://eoscms//eos/cms/store/cmst3/user/manzoni/TauPOG/11feb/ZPrimeTauTau_first4PixelVtx_sorted4power/patTuple_5_1_fL5.root',
'root://eoscms//eos/cms/store/cmst3/user/manzoni/TauPOG/11feb/ZPrimeTauTau_first4PixelVtx_sorted4power/patTuple_6_1_FJ6.root',
'root://eoscms//eos/cms/store/cmst3/user/manzoni/TauPOG/11feb/ZPrimeTauTau_first4PixelVtx_sorted4power/patTuple_7_1_jPz.root',
'root://eoscms//eos/cms/store/cmst3/user/manzoni/TauPOG/11feb/ZPrimeTauTau_first4PixelVtx_sorted4power/patTuple_8_1_gfj.root',
'root://eoscms//eos/cms/store/cmst3/user/manzoni/TauPOG/11feb/ZPrimeTauTau_first4PixelVtx_sorted4power/patTuple_9_1_c88.root',


# 'root://eoscms//eos/cms/store/cmst3/user/manzoni/TauPOG/11feb/ZPrimeTauTau_first4PixelVtx/patTuple_10_1_PJr.root',
# 'root://eoscms//eos/cms/store/cmst3/user/manzoni/TauPOG/11feb/ZPrimeTauTau_first4PixelVtx/patTuple_11_1_Qua.root',
# 'root://eoscms//eos/cms/store/cmst3/user/manzoni/TauPOG/11feb/ZPrimeTauTau_first4PixelVtx/patTuple_12_1_qKM.root',
# 'root://eoscms//eos/cms/store/cmst3/user/manzoni/TauPOG/11feb/ZPrimeTauTau_first4PixelVtx/patTuple_13_1_hBM.root',
# 'root://eoscms//eos/cms/store/cmst3/user/manzoni/TauPOG/11feb/ZPrimeTauTau_first4PixelVtx/patTuple_14_1_U63.root',
# 'root://eoscms//eos/cms/store/cmst3/user/manzoni/TauPOG/11feb/ZPrimeTauTau_first4PixelVtx/patTuple_15_1_Zih.root',
# 'root://eoscms//eos/cms/store/cmst3/user/manzoni/TauPOG/11feb/ZPrimeTauTau_first4PixelVtx/patTuple_16_1_5Ln.root',
# 'root://eoscms//eos/cms/store/cmst3/user/manzoni/TauPOG/11feb/ZPrimeTauTau_first4PixelVtx/patTuple_17_1_yJ2.root',
# 'root://eoscms//eos/cms/store/cmst3/user/manzoni/TauPOG/11feb/ZPrimeTauTau_first4PixelVtx/patTuple_18_1_Io9.root',
# 'root://eoscms//eos/cms/store/cmst3/user/manzoni/TauPOG/11feb/ZPrimeTauTau_first4PixelVtx/patTuple_1_1_04e.root',
# 'root://eoscms//eos/cms/store/cmst3/user/manzoni/TauPOG/11feb/ZPrimeTauTau_first4PixelVtx/patTuple_2_1_azS.root',
# 'root://eoscms//eos/cms/store/cmst3/user/manzoni/TauPOG/11feb/ZPrimeTauTau_first4PixelVtx/patTuple_3_1_KeH.root',
# 'root://eoscms//eos/cms/store/cmst3/user/manzoni/TauPOG/11feb/ZPrimeTauTau_first4PixelVtx/patTuple_4_1_j7t.root',
# 'root://eoscms//eos/cms/store/cmst3/user/manzoni/TauPOG/11feb/ZPrimeTauTau_first4PixelVtx/patTuple_5_1_3SP.root',
# 'root://eoscms//eos/cms/store/cmst3/user/manzoni/TauPOG/11feb/ZPrimeTauTau_first4PixelVtx/patTuple_6_1_NWB.root',
# 'root://eoscms//eos/cms/store/cmst3/user/manzoni/TauPOG/11feb/ZPrimeTauTau_first4PixelVtx/patTuple_7_1_V2q.root',
# 'root://eoscms//eos/cms/store/cmst3/user/manzoni/TauPOG/11feb/ZPrimeTauTau_first4PixelVtx/patTuple_8_1_pst.root',
# 'root://eoscms//eos/cms/store/cmst3/user/manzoni/TauPOG/11feb/ZPrimeTauTau_first4PixelVtx/patTuple_9_1_3ql.root',
# 
# 'root://eoscms//eos/cms/store/cmst3/user/manzoni/TauPOG/11feb/ZTauTau_first4PixelVtx/patTuple_10_1_U5s.root',
# 'root://eoscms//eos/cms/store/cmst3/user/manzoni/TauPOG/11feb/ZTauTau_first4PixelVtx/patTuple_11_1_S6c.root',
# 'root://eoscms//eos/cms/store/cmst3/user/manzoni/TauPOG/11feb/ZTauTau_first4PixelVtx/patTuple_12_1_659.root',
# 'root://eoscms//eos/cms/store/cmst3/user/manzoni/TauPOG/11feb/ZTauTau_first4PixelVtx/patTuple_13_1_FaM.root',
# 'root://eoscms//eos/cms/store/cmst3/user/manzoni/TauPOG/11feb/ZTauTau_first4PixelVtx/patTuple_14_1_9lZ.root',
# 'root://eoscms//eos/cms/store/cmst3/user/manzoni/TauPOG/11feb/ZTauTau_first4PixelVtx/patTuple_15_1_I7y.root',
# 'root://eoscms//eos/cms/store/cmst3/user/manzoni/TauPOG/11feb/ZTauTau_first4PixelVtx/patTuple_16_1_CBs.root',
# 'root://eoscms//eos/cms/store/cmst3/user/manzoni/TauPOG/11feb/ZTauTau_first4PixelVtx/patTuple_17_1_3Nx.root',
# 'root://eoscms//eos/cms/store/cmst3/user/manzoni/TauPOG/11feb/ZTauTau_first4PixelVtx/patTuple_18_1_oZP.root',
# 'root://eoscms//eos/cms/store/cmst3/user/manzoni/TauPOG/11feb/ZTauTau_first4PixelVtx/patTuple_19_1_1m3.root',
# 'root://eoscms//eos/cms/store/cmst3/user/manzoni/TauPOG/11feb/ZTauTau_first4PixelVtx/patTuple_1_1_1cf.root',
# 'root://eoscms//eos/cms/store/cmst3/user/manzoni/TauPOG/11feb/ZTauTau_first4PixelVtx/patTuple_20_1_NBI.root',
# 'root://eoscms//eos/cms/store/cmst3/user/manzoni/TauPOG/11feb/ZTauTau_first4PixelVtx/patTuple_2_1_m1r.root',
# 'root://eoscms//eos/cms/store/cmst3/user/manzoni/TauPOG/11feb/ZTauTau_first4PixelVtx/patTuple_3_1_9j0.root',
# 'root://eoscms//eos/cms/store/cmst3/user/manzoni/TauPOG/11feb/ZTauTau_first4PixelVtx/patTuple_4_1_wAx.root',
# 'root://eoscms//eos/cms/store/cmst3/user/manzoni/TauPOG/11feb/ZTauTau_first4PixelVtx/patTuple_5_1_YM5.root',
# 'root://eoscms//eos/cms/store/cmst3/user/manzoni/TauPOG/11feb/ZTauTau_first4PixelVtx/patTuple_6_1_RRJ.root',
# 'root://eoscms//eos/cms/store/cmst3/user/manzoni/TauPOG/11feb/ZTauTau_first4PixelVtx/patTuple_7_1_yVa.root',
# 'root://eoscms//eos/cms/store/cmst3/user/manzoni/TauPOG/11feb/ZTauTau_first4PixelVtx/patTuple_8_1_B8k.root',
# 'root://eoscms//eos/cms/store/cmst3/user/manzoni/TauPOG/11feb/ZTauTau_first4PixelVtx/patTuple_9_1_3za.root',


# 'root://eoscms//eos/cms/store/cmst3/user/manzoni/TauPOG/4feb/ZPrimeTauTau_first2PixelVtx/patTuple_10_1_rMk.root',
# 'root://eoscms//eos/cms/store/cmst3/user/manzoni/TauPOG/4feb/ZPrimeTauTau_first2PixelVtx/patTuple_11_1_7xJ.root',
# 'root://eoscms//eos/cms/store/cmst3/user/manzoni/TauPOG/4feb/ZPrimeTauTau_first2PixelVtx/patTuple_12_1_JY2.root',
# 'root://eoscms//eos/cms/store/cmst3/user/manzoni/TauPOG/4feb/ZPrimeTauTau_first2PixelVtx/patTuple_13_1_9eH.root',
# 'root://eoscms//eos/cms/store/cmst3/user/manzoni/TauPOG/4feb/ZPrimeTauTau_first2PixelVtx/patTuple_14_1_Ap0.root',
# 'root://eoscms//eos/cms/store/cmst3/user/manzoni/TauPOG/4feb/ZPrimeTauTau_first2PixelVtx/patTuple_15_1_ksL.root',
# 'root://eoscms//eos/cms/store/cmst3/user/manzoni/TauPOG/4feb/ZPrimeTauTau_first2PixelVtx/patTuple_16_1_CeV.root',
# 'root://eoscms//eos/cms/store/cmst3/user/manzoni/TauPOG/4feb/ZPrimeTauTau_first2PixelVtx/patTuple_17_1_10Z.root',
# 'root://eoscms//eos/cms/store/cmst3/user/manzoni/TauPOG/4feb/ZPrimeTauTau_first2PixelVtx/patTuple_18_1_ia3.root',
# 'root://eoscms//eos/cms/store/cmst3/user/manzoni/TauPOG/4feb/ZPrimeTauTau_first2PixelVtx/patTuple_1_1_X8V.root',
# 'root://eoscms//eos/cms/store/cmst3/user/manzoni/TauPOG/4feb/ZPrimeTauTau_first2PixelVtx/patTuple_2_1_i8m.root',
# 'root://eoscms//eos/cms/store/cmst3/user/manzoni/TauPOG/4feb/ZPrimeTauTau_first2PixelVtx/patTuple_3_1_eNb.root',
# 'root://eoscms//eos/cms/store/cmst3/user/manzoni/TauPOG/4feb/ZPrimeTauTau_first2PixelVtx/patTuple_4_1_TJI.root',
# 'root://eoscms//eos/cms/store/cmst3/user/manzoni/TauPOG/4feb/ZPrimeTauTau_first2PixelVtx/patTuple_5_1_IpH.root',
# 'root://eoscms//eos/cms/store/cmst3/user/manzoni/TauPOG/4feb/ZPrimeTauTau_first2PixelVtx/patTuple_6_1_j9o.root',
# 'root://eoscms//eos/cms/store/cmst3/user/manzoni/TauPOG/4feb/ZPrimeTauTau_first2PixelVtx/patTuple_7_1_KlL.root',
# 'root://eoscms//eos/cms/store/cmst3/user/manzoni/TauPOG/4feb/ZPrimeTauTau_first2PixelVtx/patTuple_8_1_45n.root',
# 'root://eoscms//eos/cms/store/cmst3/user/manzoni/TauPOG/4feb/ZPrimeTauTau_first2PixelVtx/patTuple_9_1_KFY.root',
# 
# 
# 
# 'root://eoscms//eos/cms/store/cmst3/user/manzoni/TauPOG/4feb/ZTauTau_first2PixelVtx/patTuple_10_1_jgn.root',
# 'root://eoscms//eos/cms/store/cmst3/user/manzoni/TauPOG/4feb/ZTauTau_first2PixelVtx/patTuple_11_1_n65.root',
# 'root://eoscms//eos/cms/store/cmst3/user/manzoni/TauPOG/4feb/ZTauTau_first2PixelVtx/patTuple_12_1_sRZ.root',
# 'root://eoscms//eos/cms/store/cmst3/user/manzoni/TauPOG/4feb/ZTauTau_first2PixelVtx/patTuple_13_1_Dza.root',
# 'root://eoscms//eos/cms/store/cmst3/user/manzoni/TauPOG/4feb/ZTauTau_first2PixelVtx/patTuple_14_1_NxH.root',
# 'root://eoscms//eos/cms/store/cmst3/user/manzoni/TauPOG/4feb/ZTauTau_first2PixelVtx/patTuple_15_1_14u.root',
# 'root://eoscms//eos/cms/store/cmst3/user/manzoni/TauPOG/4feb/ZTauTau_first2PixelVtx/patTuple_16_1_xKC.root',
# 'root://eoscms//eos/cms/store/cmst3/user/manzoni/TauPOG/4feb/ZTauTau_first2PixelVtx/patTuple_17_1_cYk.root',
# 'root://eoscms//eos/cms/store/cmst3/user/manzoni/TauPOG/4feb/ZTauTau_first2PixelVtx/patTuple_18_1_L45.root',
# 'root://eoscms//eos/cms/store/cmst3/user/manzoni/TauPOG/4feb/ZTauTau_first2PixelVtx/patTuple_19_1_5U3.root',
# 'root://eoscms//eos/cms/store/cmst3/user/manzoni/TauPOG/4feb/ZTauTau_first2PixelVtx/patTuple_1_1_oCK.root',
# 'root://eoscms//eos/cms/store/cmst3/user/manzoni/TauPOG/4feb/ZTauTau_first2PixelVtx/patTuple_20_1_NGV.root',
# 'root://eoscms//eos/cms/store/cmst3/user/manzoni/TauPOG/4feb/ZTauTau_first2PixelVtx/patTuple_2_1_vpU.root',
# 'root://eoscms//eos/cms/store/cmst3/user/manzoni/TauPOG/4feb/ZTauTau_first2PixelVtx/patTuple_3_1_Eg3.root',
# 'root://eoscms//eos/cms/store/cmst3/user/manzoni/TauPOG/4feb/ZTauTau_first2PixelVtx/patTuple_4_1_QZ9.root',
# 'root://eoscms//eos/cms/store/cmst3/user/manzoni/TauPOG/4feb/ZTauTau_first2PixelVtx/patTuple_5_1_J6z.root',
# 'root://eoscms//eos/cms/store/cmst3/user/manzoni/TauPOG/4feb/ZTauTau_first2PixelVtx/patTuple_6_1_1H6.root',
# 'root://eoscms//eos/cms/store/cmst3/user/manzoni/TauPOG/4feb/ZTauTau_first2PixelVtx/patTuple_7_1_G3G.root',
# 'root://eoscms//eos/cms/store/cmst3/user/manzoni/TauPOG/4feb/ZTauTau_first2PixelVtx/patTuple_8_1_JBZ.root',
# 'root://eoscms//eos/cms/store/cmst3/user/manzoni/TauPOG/4feb/ZTauTau_first2PixelVtx/patTuple_9_1_07C.root',






# 'root://eoscms//eos/cms/store/cmst3/user/manzoni/TauPOG/4feb/ZPrimeTauTau_first4PixelVtx/patTuple_10_1_F1h.root',
# 'root://eoscms//eos/cms/store/cmst3/user/manzoni/TauPOG/4feb/ZPrimeTauTau_first4PixelVtx/patTuple_11_1_gLa.root',
# 'root://eoscms//eos/cms/store/cmst3/user/manzoni/TauPOG/4feb/ZPrimeTauTau_first4PixelVtx/patTuple_12_1_oZN.root',
# 'root://eoscms//eos/cms/store/cmst3/user/manzoni/TauPOG/4feb/ZPrimeTauTau_first4PixelVtx/patTuple_13_1_Y17.root',
# 'root://eoscms//eos/cms/store/cmst3/user/manzoni/TauPOG/4feb/ZPrimeTauTau_first4PixelVtx/patTuple_14_1_Mmb.root',
# 'root://eoscms//eos/cms/store/cmst3/user/manzoni/TauPOG/4feb/ZPrimeTauTau_first4PixelVtx/patTuple_15_1_gCA.root',
# 'root://eoscms//eos/cms/store/cmst3/user/manzoni/TauPOG/4feb/ZPrimeTauTau_first4PixelVtx/patTuple_16_1_d7O.root',
# 'root://eoscms//eos/cms/store/cmst3/user/manzoni/TauPOG/4feb/ZPrimeTauTau_first4PixelVtx/patTuple_17_1_hNj.root',
# 'root://eoscms//eos/cms/store/cmst3/user/manzoni/TauPOG/4feb/ZPrimeTauTau_first4PixelVtx/patTuple_18_1_go5.root',
# 'root://eoscms//eos/cms/store/cmst3/user/manzoni/TauPOG/4feb/ZPrimeTauTau_first4PixelVtx/patTuple_1_1_Fjk.root',
# 'root://eoscms//eos/cms/store/cmst3/user/manzoni/TauPOG/4feb/ZPrimeTauTau_first4PixelVtx/patTuple_2_1_xHE.root',
# 'root://eoscms//eos/cms/store/cmst3/user/manzoni/TauPOG/4feb/ZPrimeTauTau_first4PixelVtx/patTuple_3_1_Yxn.root',
# 'root://eoscms//eos/cms/store/cmst3/user/manzoni/TauPOG/4feb/ZPrimeTauTau_first4PixelVtx/patTuple_4_1_SdR.root',
# 'root://eoscms//eos/cms/store/cmst3/user/manzoni/TauPOG/4feb/ZPrimeTauTau_first4PixelVtx/patTuple_5_1_0Na.root',
# 'root://eoscms//eos/cms/store/cmst3/user/manzoni/TauPOG/4feb/ZPrimeTauTau_first4PixelVtx/patTuple_6_1_em7.root',
# 'root://eoscms//eos/cms/store/cmst3/user/manzoni/TauPOG/4feb/ZPrimeTauTau_first4PixelVtx/patTuple_7_1_xbo.root',
# 'root://eoscms//eos/cms/store/cmst3/user/manzoni/TauPOG/4feb/ZPrimeTauTau_first4PixelVtx/patTuple_8_1_eFY.root',
# 'root://eoscms//eos/cms/store/cmst3/user/manzoni/TauPOG/4feb/ZPrimeTauTau_first4PixelVtx/patTuple_9_1_w0U.root',
# 
# 
# 
# 'root://eoscms//eos/cms/store/cmst3/user/manzoni/TauPOG/4feb/ZTauTau_first4PixelVtx/patTuple_10_1_fcG.root',
# 'root://eoscms//eos/cms/store/cmst3/user/manzoni/TauPOG/4feb/ZTauTau_first4PixelVtx/patTuple_11_1_LRt.root',
# 'root://eoscms//eos/cms/store/cmst3/user/manzoni/TauPOG/4feb/ZTauTau_first4PixelVtx/patTuple_12_1_jAz.root',
# 'root://eoscms//eos/cms/store/cmst3/user/manzoni/TauPOG/4feb/ZTauTau_first4PixelVtx/patTuple_13_1_nJs.root',
# 'root://eoscms//eos/cms/store/cmst3/user/manzoni/TauPOG/4feb/ZTauTau_first4PixelVtx/patTuple_14_1_u2G.root',
# 'root://eoscms//eos/cms/store/cmst3/user/manzoni/TauPOG/4feb/ZTauTau_first4PixelVtx/patTuple_15_1_CM1.root',
# 'root://eoscms//eos/cms/store/cmst3/user/manzoni/TauPOG/4feb/ZTauTau_first4PixelVtx/patTuple_16_1_cfL.root',
# 'root://eoscms//eos/cms/store/cmst3/user/manzoni/TauPOG/4feb/ZTauTau_first4PixelVtx/patTuple_17_1_GJI.root',
# 'root://eoscms//eos/cms/store/cmst3/user/manzoni/TauPOG/4feb/ZTauTau_first4PixelVtx/patTuple_18_1_j8g.root',
# 'root://eoscms//eos/cms/store/cmst3/user/manzoni/TauPOG/4feb/ZTauTau_first4PixelVtx/patTuple_19_1_Sp7.root',
# 'root://eoscms//eos/cms/store/cmst3/user/manzoni/TauPOG/4feb/ZTauTau_first4PixelVtx/patTuple_1_1_lKe.root',
# 'root://eoscms//eos/cms/store/cmst3/user/manzoni/TauPOG/4feb/ZTauTau_first4PixelVtx/patTuple_20_1_CR5.root',
# 'root://eoscms//eos/cms/store/cmst3/user/manzoni/TauPOG/4feb/ZTauTau_first4PixelVtx/patTuple_2_1_D7I.root',
# 'root://eoscms//eos/cms/store/cmst3/user/manzoni/TauPOG/4feb/ZTauTau_first4PixelVtx/patTuple_3_1_Euc.root',
# 'root://eoscms//eos/cms/store/cmst3/user/manzoni/TauPOG/4feb/ZTauTau_first4PixelVtx/patTuple_4_1_6T2.root',
# 'root://eoscms//eos/cms/store/cmst3/user/manzoni/TauPOG/4feb/ZTauTau_first4PixelVtx/patTuple_5_1_CSx.root',
# 'root://eoscms//eos/cms/store/cmst3/user/manzoni/TauPOG/4feb/ZTauTau_first4PixelVtx/patTuple_6_1_S9H.root',
# 'root://eoscms//eos/cms/store/cmst3/user/manzoni/TauPOG/4feb/ZTauTau_first4PixelVtx/patTuple_7_1_Hm7.root',
# 'root://eoscms//eos/cms/store/cmst3/user/manzoni/TauPOG/4feb/ZTauTau_first4PixelVtx/patTuple_8_1_dta.root',
# 'root://eoscms//eos/cms/store/cmst3/user/manzoni/TauPOG/4feb/ZTauTau_first4PixelVtx/patTuple_9_1_O6Q.root',




# 'root://eoscms//eos/cms/store/cmst3/user/manzoni/TauPOG/4feb/ZTauTau_offlineVtx/patTuple_10_1_pdi.root',
# 'root://eoscms//eos/cms/store/cmst3/user/manzoni/TauPOG/4feb/ZTauTau_offlineVtx/patTuple_11_1_Wmj.root',
# 'root://eoscms//eos/cms/store/cmst3/user/manzoni/TauPOG/4feb/ZTauTau_offlineVtx/patTuple_12_1_LmE.root',
# 'root://eoscms//eos/cms/store/cmst3/user/manzoni/TauPOG/4feb/ZTauTau_offlineVtx/patTuple_13_1_YZI.root',
# 'root://eoscms//eos/cms/store/cmst3/user/manzoni/TauPOG/4feb/ZTauTau_offlineVtx/patTuple_14_1_BNj.root',
# 'root://eoscms//eos/cms/store/cmst3/user/manzoni/TauPOG/4feb/ZTauTau_offlineVtx/patTuple_15_1_Gou.root',
# 'root://eoscms//eos/cms/store/cmst3/user/manzoni/TauPOG/4feb/ZTauTau_offlineVtx/patTuple_16_1_Nma.root',
# 'root://eoscms//eos/cms/store/cmst3/user/manzoni/TauPOG/4feb/ZTauTau_offlineVtx/patTuple_17_1_0TE.root',
# 'root://eoscms//eos/cms/store/cmst3/user/manzoni/TauPOG/4feb/ZTauTau_offlineVtx/patTuple_18_1_kda.root',
# 'root://eoscms//eos/cms/store/cmst3/user/manzoni/TauPOG/4feb/ZTauTau_offlineVtx/patTuple_19_1_lfg.root',
# 'root://eoscms//eos/cms/store/cmst3/user/manzoni/TauPOG/4feb/ZTauTau_offlineVtx/patTuple_1_1_9BQ.root',
# 'root://eoscms//eos/cms/store/cmst3/user/manzoni/TauPOG/4feb/ZTauTau_offlineVtx/patTuple_20_1_tua.root',
# 'root://eoscms//eos/cms/store/cmst3/user/manzoni/TauPOG/4feb/ZTauTau_offlineVtx/patTuple_2_1_oBZ.root',
# 'root://eoscms//eos/cms/store/cmst3/user/manzoni/TauPOG/4feb/ZTauTau_offlineVtx/patTuple_3_1_32r.root',
# 'root://eoscms//eos/cms/store/cmst3/user/manzoni/TauPOG/4feb/ZTauTau_offlineVtx/patTuple_4_1_vad.root',
# 'root://eoscms//eos/cms/store/cmst3/user/manzoni/TauPOG/4feb/ZTauTau_offlineVtx/patTuple_5_1_Wbg.root',
# 'root://eoscms//eos/cms/store/cmst3/user/manzoni/TauPOG/4feb/ZTauTau_offlineVtx/patTuple_6_1_nA1.root',
# 'root://eoscms//eos/cms/store/cmst3/user/manzoni/TauPOG/4feb/ZTauTau_offlineVtx/patTuple_7_1_ZEe.root',
# 'root://eoscms//eos/cms/store/cmst3/user/manzoni/TauPOG/4feb/ZTauTau_offlineVtx/patTuple_8_1_7CZ.root',
# 'root://eoscms//eos/cms/store/cmst3/user/manzoni/TauPOG/4feb/ZTauTau_offlineVtx/patTuple_9_1_q4r.root',
# 
# 'root://eoscms//eos/cms/store/cmst3/user/manzoni/TauPOG/4feb/ZPrimeTauTau_offlineVtx/patTuple_10_1_mZO.root',
# 'root://eoscms//eos/cms/store/cmst3/user/manzoni/TauPOG/4feb/ZPrimeTauTau_offlineVtx/patTuple_11_1_uVS.root',
# 'root://eoscms//eos/cms/store/cmst3/user/manzoni/TauPOG/4feb/ZPrimeTauTau_offlineVtx/patTuple_12_1_Ua1.root',
# 'root://eoscms//eos/cms/store/cmst3/user/manzoni/TauPOG/4feb/ZPrimeTauTau_offlineVtx/patTuple_13_1_AMD.root',
# 'root://eoscms//eos/cms/store/cmst3/user/manzoni/TauPOG/4feb/ZPrimeTauTau_offlineVtx/patTuple_14_1_99p.root',
# 'root://eoscms//eos/cms/store/cmst3/user/manzoni/TauPOG/4feb/ZPrimeTauTau_offlineVtx/patTuple_15_1_Eaq.root',
# 'root://eoscms//eos/cms/store/cmst3/user/manzoni/TauPOG/4feb/ZPrimeTauTau_offlineVtx/patTuple_16_1_G0O.root',
# 'root://eoscms//eos/cms/store/cmst3/user/manzoni/TauPOG/4feb/ZPrimeTauTau_offlineVtx/patTuple_17_1_HUc.root',
# 'root://eoscms//eos/cms/store/cmst3/user/manzoni/TauPOG/4feb/ZPrimeTauTau_offlineVtx/patTuple_18_1_z3Y.root',
# 'root://eoscms//eos/cms/store/cmst3/user/manzoni/TauPOG/4feb/ZPrimeTauTau_offlineVtx/patTuple_1_1_2bu.root',
# 'root://eoscms//eos/cms/store/cmst3/user/manzoni/TauPOG/4feb/ZPrimeTauTau_offlineVtx/patTuple_2_1_uQm.root',
# 'root://eoscms//eos/cms/store/cmst3/user/manzoni/TauPOG/4feb/ZPrimeTauTau_offlineVtx/patTuple_3_1_iQc.root',
# 'root://eoscms//eos/cms/store/cmst3/user/manzoni/TauPOG/4feb/ZPrimeTauTau_offlineVtx/patTuple_4_1_SQh.root',
# 'root://eoscms//eos/cms/store/cmst3/user/manzoni/TauPOG/4feb/ZPrimeTauTau_offlineVtx/patTuple_5_1_fGQ.root',
# 'root://eoscms//eos/cms/store/cmst3/user/manzoni/TauPOG/4feb/ZPrimeTauTau_offlineVtx/patTuple_6_1_WzO.root',
# 'root://eoscms//eos/cms/store/cmst3/user/manzoni/TauPOG/4feb/ZPrimeTauTau_offlineVtx/patTuple_7_1_svn.root',
# 'root://eoscms//eos/cms/store/cmst3/user/manzoni/TauPOG/4feb/ZPrimeTauTau_offlineVtx/patTuple_8_1_GAo.root',
# 'root://eoscms//eos/cms/store/cmst3/user/manzoni/TauPOG/4feb/ZPrimeTauTau_offlineVtx/patTuple_9_1_CJA.root',



# 'root://eoscms//eos/cms/store/cmst3/user/manzoni/TauPOG/4feb/ZTauTau/patTuple_10_1_LHx.root',
# 'root://eoscms//eos/cms/store/cmst3/user/manzoni/TauPOG/4feb/ZTauTau/patTuple_11_1_Ycl.root',
# 'root://eoscms//eos/cms/store/cmst3/user/manzoni/TauPOG/4feb/ZTauTau/patTuple_12_1_qVI.root',
# 'root://eoscms//eos/cms/store/cmst3/user/manzoni/TauPOG/4feb/ZTauTau/patTuple_13_1_Qpq.root',
# 'root://eoscms//eos/cms/store/cmst3/user/manzoni/TauPOG/4feb/ZTauTau/patTuple_14_1_lex.root',
# 'root://eoscms//eos/cms/store/cmst3/user/manzoni/TauPOG/4feb/ZTauTau/patTuple_15_1_q5M.root',
# 'root://eoscms//eos/cms/store/cmst3/user/manzoni/TauPOG/4feb/ZTauTau/patTuple_16_1_tY1.root',
# 'root://eoscms//eos/cms/store/cmst3/user/manzoni/TauPOG/4feb/ZTauTau/patTuple_17_1_nox.root',
# 'root://eoscms//eos/cms/store/cmst3/user/manzoni/TauPOG/4feb/ZTauTau/patTuple_18_1_api.root',
# 'root://eoscms//eos/cms/store/cmst3/user/manzoni/TauPOG/4feb/ZTauTau/patTuple_19_1_NW6.root',
# 'root://eoscms//eos/cms/store/cmst3/user/manzoni/TauPOG/4feb/ZTauTau/patTuple_1_1_4Hj.root',
# 'root://eoscms//eos/cms/store/cmst3/user/manzoni/TauPOG/4feb/ZTauTau/patTuple_20_1_fkO.root',
# 'root://eoscms//eos/cms/store/cmst3/user/manzoni/TauPOG/4feb/ZTauTau/patTuple_21_1_cte.root',
# 'root://eoscms//eos/cms/store/cmst3/user/manzoni/TauPOG/4feb/ZTauTau/patTuple_22_1_lv2.root',
# 'root://eoscms//eos/cms/store/cmst3/user/manzoni/TauPOG/4feb/ZTauTau/patTuple_2_1_rtD.root',
# 'root://eoscms//eos/cms/store/cmst3/user/manzoni/TauPOG/4feb/ZTauTau/patTuple_3_1_SKb.root',
# 'root://eoscms//eos/cms/store/cmst3/user/manzoni/TauPOG/4feb/ZTauTau/patTuple_4_1_Msh.root',
# 'root://eoscms//eos/cms/store/cmst3/user/manzoni/TauPOG/4feb/ZTauTau/patTuple_5_1_2kp.root',
# 'root://eoscms//eos/cms/store/cmst3/user/manzoni/TauPOG/4feb/ZTauTau/patTuple_6_1_7Il.root',
# 'root://eoscms//eos/cms/store/cmst3/user/manzoni/TauPOG/4feb/ZTauTau/patTuple_7_1_hSJ.root',
# 'root://eoscms//eos/cms/store/cmst3/user/manzoni/TauPOG/4feb/ZTauTau/patTuple_8_1_x5r.root',
# 'root://eoscms//eos/cms/store/cmst3/user/manzoni/TauPOG/4feb/ZTauTau/patTuple_9_1_Fu2.root',
# 
# 
# 'root://eoscms//eos/cms/store/cmst3/user/manzoni/TauPOG/4feb/ZPrimeTauTau/patTuple_10_1_8Vv.root',
# 'root://eoscms//eos/cms/store/cmst3/user/manzoni/TauPOG/4feb/ZPrimeTauTau/patTuple_11_1_dwD.root',
# 'root://eoscms//eos/cms/store/cmst3/user/manzoni/TauPOG/4feb/ZPrimeTauTau/patTuple_12_1_r8g.root',
# 'root://eoscms//eos/cms/store/cmst3/user/manzoni/TauPOG/4feb/ZPrimeTauTau/patTuple_13_1_W7c.root',
# 'root://eoscms//eos/cms/store/cmst3/user/manzoni/TauPOG/4feb/ZPrimeTauTau/patTuple_14_1_yBh.root',
# 'root://eoscms//eos/cms/store/cmst3/user/manzoni/TauPOG/4feb/ZPrimeTauTau/patTuple_15_1_knQ.root',
# 'root://eoscms//eos/cms/store/cmst3/user/manzoni/TauPOG/4feb/ZPrimeTauTau/patTuple_16_1_yjB.root',
# 'root://eoscms//eos/cms/store/cmst3/user/manzoni/TauPOG/4feb/ZPrimeTauTau/patTuple_17_1_4gh.root',
# 'root://eoscms//eos/cms/store/cmst3/user/manzoni/TauPOG/4feb/ZPrimeTauTau/patTuple_18_1_po0.root',
# 'root://eoscms//eos/cms/store/cmst3/user/manzoni/TauPOG/4feb/ZPrimeTauTau/patTuple_19_1_vmQ.root',
# 'root://eoscms//eos/cms/store/cmst3/user/manzoni/TauPOG/4feb/ZPrimeTauTau/patTuple_1_1_mqP.root',
# 'root://eoscms//eos/cms/store/cmst3/user/manzoni/TauPOG/4feb/ZPrimeTauTau/patTuple_1_2_GFQ.root',
# 'root://eoscms//eos/cms/store/cmst3/user/manzoni/TauPOG/4feb/ZPrimeTauTau/patTuple_20_1_5aG.root',
# 'root://eoscms//eos/cms/store/cmst3/user/manzoni/TauPOG/4feb/ZPrimeTauTau/patTuple_21_1_sUh.root',
# 'root://eoscms//eos/cms/store/cmst3/user/manzoni/TauPOG/4feb/ZPrimeTauTau/patTuple_22_1_Fpk.root',
# 'root://eoscms//eos/cms/store/cmst3/user/manzoni/TauPOG/4feb/ZPrimeTauTau/patTuple_23_1_U8Z.root',
# 'root://eoscms//eos/cms/store/cmst3/user/manzoni/TauPOG/4feb/ZPrimeTauTau/patTuple_24_1_Jpe.root',
# 'root://eoscms//eos/cms/store/cmst3/user/manzoni/TauPOG/4feb/ZPrimeTauTau/patTuple_25_1_9sp.root',
# 'root://eoscms//eos/cms/store/cmst3/user/manzoni/TauPOG/4feb/ZPrimeTauTau/patTuple_26_1_BSi.root',
# 'root://eoscms//eos/cms/store/cmst3/user/manzoni/TauPOG/4feb/ZPrimeTauTau/patTuple_2_1_BAq.root',
# 'root://eoscms//eos/cms/store/cmst3/user/manzoni/TauPOG/4feb/ZPrimeTauTau/patTuple_3_1_UYn.root',
# 'root://eoscms//eos/cms/store/cmst3/user/manzoni/TauPOG/4feb/ZPrimeTauTau/patTuple_4_1_URK.root',
# 'root://eoscms//eos/cms/store/cmst3/user/manzoni/TauPOG/4feb/ZPrimeTauTau/patTuple_5_1_H0c.root',
# 'root://eoscms//eos/cms/store/cmst3/user/manzoni/TauPOG/4feb/ZPrimeTauTau/patTuple_6_1_hX8.root',
# 'root://eoscms//eos/cms/store/cmst3/user/manzoni/TauPOG/4feb/ZPrimeTauTau/patTuple_7_1_wLZ.root',
# 'root://eoscms//eos/cms/store/cmst3/user/manzoni/TauPOG/4feb/ZPrimeTauTau/patTuple_8_1_1kV.root',
# 'root://eoscms//eos/cms/store/cmst3/user/manzoni/TauPOG/4feb/ZPrimeTauTau/patTuple_9_1_XBq.root',
# 
# 
# 
# 
# 
# 
# 
# 


# 
# 'root://eoscms//eos/cms/store/group/phys_tau/CMSSW_5_3_x/TauTriggerStudies/31jan/ZprimeTautau/patTuple_10_1_8xh.root',
# 'root://eoscms//eos/cms/store/group/phys_tau/CMSSW_5_3_x/TauTriggerStudies/31jan/ZprimeTautau/patTuple_11_1_h35.root',
# 'root://eoscms//eos/cms/store/group/phys_tau/CMSSW_5_3_x/TauTriggerStudies/31jan/ZprimeTautau/patTuple_12_1_GP0.root',
# 'root://eoscms//eos/cms/store/group/phys_tau/CMSSW_5_3_x/TauTriggerStudies/31jan/ZprimeTautau/patTuple_13_1_Ov0.root',
# 'root://eoscms//eos/cms/store/group/phys_tau/CMSSW_5_3_x/TauTriggerStudies/31jan/ZprimeTautau/patTuple_14_1_14l.root',
# 'root://eoscms//eos/cms/store/group/phys_tau/CMSSW_5_3_x/TauTriggerStudies/31jan/ZprimeTautau/patTuple_15_1_GML.root',
# 'root://eoscms//eos/cms/store/group/phys_tau/CMSSW_5_3_x/TauTriggerStudies/31jan/ZprimeTautau/patTuple_16_1_JGW.root',
# 'root://eoscms//eos/cms/store/group/phys_tau/CMSSW_5_3_x/TauTriggerStudies/31jan/ZprimeTautau/patTuple_1_1_9SF.root',
# 'root://eoscms//eos/cms/store/group/phys_tau/CMSSW_5_3_x/TauTriggerStudies/31jan/ZprimeTautau/patTuple_2_1_XbM.root',
# 'root://eoscms//eos/cms/store/group/phys_tau/CMSSW_5_3_x/TauTriggerStudies/31jan/ZprimeTautau/patTuple_3_1_a7r.root',
# 'root://eoscms//eos/cms/store/group/phys_tau/CMSSW_5_3_x/TauTriggerStudies/31jan/ZprimeTautau/patTuple_4_1_ieH.root',
# 'root://eoscms//eos/cms/store/group/phys_tau/CMSSW_5_3_x/TauTriggerStudies/31jan/ZprimeTautau/patTuple_5_1_ADv.root',
# 'root://eoscms//eos/cms/store/group/phys_tau/CMSSW_5_3_x/TauTriggerStudies/31jan/ZprimeTautau/patTuple_6_1_lNs.root',
# 'root://eoscms//eos/cms/store/group/phys_tau/CMSSW_5_3_x/TauTriggerStudies/31jan/ZprimeTautau/patTuple_7_1_Mvf.root',
# 'root://eoscms//eos/cms/store/group/phys_tau/CMSSW_5_3_x/TauTriggerStudies/31jan/ZprimeTautau/patTuple_8_1_NLn.root',
# 'root://eoscms//eos/cms/store/group/phys_tau/CMSSW_5_3_x/TauTriggerStudies/31jan/ZprimeTautau/patTuple_9_1_93Y.root',
# 
# 'root://eoscms//eos/cms/store/group/phys_tau/CMSSW_5_3_x/TauTriggerStudies/31jan/Ztautau/patTuple_10_1_UKv.root',
# 'root://eoscms//eos/cms/store/group/phys_tau/CMSSW_5_3_x/TauTriggerStudies/31jan/Ztautau/patTuple_11_1_0vi.root',
# 'root://eoscms//eos/cms/store/group/phys_tau/CMSSW_5_3_x/TauTriggerStudies/31jan/Ztautau/patTuple_12_1_Kn2.root',
# 'root://eoscms//eos/cms/store/group/phys_tau/CMSSW_5_3_x/TauTriggerStudies/31jan/Ztautau/patTuple_13_1_i2o.root',
# 'root://eoscms//eos/cms/store/group/phys_tau/CMSSW_5_3_x/TauTriggerStudies/31jan/Ztautau/patTuple_14_1_mFs.root',
# 'root://eoscms//eos/cms/store/group/phys_tau/CMSSW_5_3_x/TauTriggerStudies/31jan/Ztautau/patTuple_1_1_byD.root',
# 'root://eoscms//eos/cms/store/group/phys_tau/CMSSW_5_3_x/TauTriggerStudies/31jan/Ztautau/patTuple_2_1_jY2.root',
# 'root://eoscms//eos/cms/store/group/phys_tau/CMSSW_5_3_x/TauTriggerStudies/31jan/Ztautau/patTuple_3_1_fNN.root',
# 'root://eoscms//eos/cms/store/group/phys_tau/CMSSW_5_3_x/TauTriggerStudies/31jan/Ztautau/patTuple_4_1_qZ0.root',
# 'root://eoscms//eos/cms/store/group/phys_tau/CMSSW_5_3_x/TauTriggerStudies/31jan/Ztautau/patTuple_5_1_Qfc.root',
# 'root://eoscms//eos/cms/store/group/phys_tau/CMSSW_5_3_x/TauTriggerStudies/31jan/Ztautau/patTuple_6_2_ey9.root',
# 'root://eoscms//eos/cms/store/group/phys_tau/CMSSW_5_3_x/TauTriggerStudies/31jan/Ztautau/patTuple_7_1_oof.root',
# 'root://eoscms//eos/cms/store/group/phys_tau/CMSSW_5_3_x/TauTriggerStudies/31jan/Ztautau/patTuple_8_1_Yzb.root',
# 'root://eoscms//eos/cms/store/group/phys_tau/CMSSW_5_3_x/TauTriggerStudies/31jan/Ztautau/patTuple_9_1_Xy6.root',
# 
# 





















# 'root://eoscms//eos/cms/store/group/phys_tau/CMSSW_5_3_x/TauTriggerStudies/Ztautau_mc_v6/patTuple_10_1_AXC.root',
# 'root://eoscms//eos/cms/store/group/phys_tau/CMSSW_5_3_x/TauTriggerStudies/Ztautau_mc_v6/patTuple_11_1_a1D.root',
# 'root://eoscms//eos/cms/store/group/phys_tau/CMSSW_5_3_x/TauTriggerStudies/Ztautau_mc_v6/patTuple_12_1_8M5.root',
# 'root://eoscms//eos/cms/store/group/phys_tau/CMSSW_5_3_x/TauTriggerStudies/Ztautau_mc_v6/patTuple_13_1_JYi.root',
# 'root://eoscms//eos/cms/store/group/phys_tau/CMSSW_5_3_x/TauTriggerStudies/Ztautau_mc_v6/patTuple_14_1_7AN.root',
# 'root://eoscms//eos/cms/store/group/phys_tau/CMSSW_5_3_x/TauTriggerStudies/Ztautau_mc_v6/patTuple_15_1_y07.root',
# 'root://eoscms//eos/cms/store/group/phys_tau/CMSSW_5_3_x/TauTriggerStudies/Ztautau_mc_v6/patTuple_16_1_1TF.root',
# 'root://eoscms//eos/cms/store/group/phys_tau/CMSSW_5_3_x/TauTriggerStudies/Ztautau_mc_v6/patTuple_17_1_Noq.root',
# 'root://eoscms//eos/cms/store/group/phys_tau/CMSSW_5_3_x/TauTriggerStudies/Ztautau_mc_v6/patTuple_18_1_N3G.root',
# 'root://eoscms//eos/cms/store/group/phys_tau/CMSSW_5_3_x/TauTriggerStudies/Ztautau_mc_v6/patTuple_19_1_I3Z.root',
# 'root://eoscms//eos/cms/store/group/phys_tau/CMSSW_5_3_x/TauTriggerStudies/Ztautau_mc_v6/patTuple_1_1_lnT.root',
# 'root://eoscms//eos/cms/store/group/phys_tau/CMSSW_5_3_x/TauTriggerStudies/Ztautau_mc_v6/patTuple_20_1_3f6.root',
# 'root://eoscms//eos/cms/store/group/phys_tau/CMSSW_5_3_x/TauTriggerStudies/Ztautau_mc_v6/patTuple_2_1_x53.root',
# 'root://eoscms//eos/cms/store/group/phys_tau/CMSSW_5_3_x/TauTriggerStudies/Ztautau_mc_v6/patTuple_3_1_raU.root',
# 'root://eoscms//eos/cms/store/group/phys_tau/CMSSW_5_3_x/TauTriggerStudies/Ztautau_mc_v6/patTuple_4_1_TfY.root',
# 'root://eoscms//eos/cms/store/group/phys_tau/CMSSW_5_3_x/TauTriggerStudies/Ztautau_mc_v6/patTuple_5_1_wsE.root',
# 'root://eoscms//eos/cms/store/group/phys_tau/CMSSW_5_3_x/TauTriggerStudies/Ztautau_mc_v6/patTuple_6_1_yyo.root',
# 'root://eoscms//eos/cms/store/group/phys_tau/CMSSW_5_3_x/TauTriggerStudies/Ztautau_mc_v6/patTuple_7_1_D1e.root',
# 'root://eoscms//eos/cms/store/group/phys_tau/CMSSW_5_3_x/TauTriggerStudies/Ztautau_mc_v6/patTuple_8_1_lXv.root',
# 'root://eoscms//eos/cms/store/group/phys_tau/CMSSW_5_3_x/TauTriggerStudies/Ztautau_mc_v6/patTuple_9_1_Pzh.root',
# 
# 
# 'root://eoscms//eos/cms/store/group/phys_tau/CMSSW_5_3_x/TauTriggerStudies/Ztautau_mc_v5/patTuple_1_1_eLb.root',
# 'root://eoscms//eos/cms/store/group/phys_tau/CMSSW_5_3_x/TauTriggerStudies/Ztautau_mc_v5/patTuple_2_1_6w7.root',
# 'root://eoscms//eos/cms/store/group/phys_tau/CMSSW_5_3_x/TauTriggerStudies/Ztautau_mc_v5/patTuple_3_1_nNG.root',
# 'root://eoscms//eos/cms/store/group/phys_tau/CMSSW_5_3_x/TauTriggerStudies/Ztautau_mc_v5/patTuple_4_1_AEP.root',


# 'root://eoscms//eos/cms/store/group/phys_tau/CMSSW_5_3_x/TauTriggerStudies/Ztautau_mc_v4/patTuple_10_1_JX2.root',
# 'root://eoscms//eos/cms/store/group/phys_tau/CMSSW_5_3_x/TauTriggerStudies/Ztautau_mc_v4/patTuple_11_1_N2T.root',
# 'root://eoscms//eos/cms/store/group/phys_tau/CMSSW_5_3_x/TauTriggerStudies/Ztautau_mc_v4/patTuple_12_1_Zx5.root',
# 'root://eoscms//eos/cms/store/group/phys_tau/CMSSW_5_3_x/TauTriggerStudies/Ztautau_mc_v4/patTuple_13_1_aBL.root',
# 'root://eoscms//eos/cms/store/group/phys_tau/CMSSW_5_3_x/TauTriggerStudies/Ztautau_mc_v4/patTuple_14_1_1jN.root',
# 'root://eoscms//eos/cms/store/group/phys_tau/CMSSW_5_3_x/TauTriggerStudies/Ztautau_mc_v4/patTuple_15_1_oax.root',
# 'root://eoscms//eos/cms/store/group/phys_tau/CMSSW_5_3_x/TauTriggerStudies/Ztautau_mc_v4/patTuple_16_1_OJ5.root',
# 'root://eoscms//eos/cms/store/group/phys_tau/CMSSW_5_3_x/TauTriggerStudies/Ztautau_mc_v4/patTuple_17_1_Yrp.root',
# 'root://eoscms//eos/cms/store/group/phys_tau/CMSSW_5_3_x/TauTriggerStudies/Ztautau_mc_v4/patTuple_18_1_Oyd.root',
# 'root://eoscms//eos/cms/store/group/phys_tau/CMSSW_5_3_x/TauTriggerStudies/Ztautau_mc_v4/patTuple_19_1_KCn.root',
# 'root://eoscms//eos/cms/store/group/phys_tau/CMSSW_5_3_x/TauTriggerStudies/Ztautau_mc_v4/patTuple_1_1_ios.root',
# 'root://eoscms//eos/cms/store/group/phys_tau/CMSSW_5_3_x/TauTriggerStudies/Ztautau_mc_v4/patTuple_20_1_i1j.root',
# 'root://eoscms//eos/cms/store/group/phys_tau/CMSSW_5_3_x/TauTriggerStudies/Ztautau_mc_v4/patTuple_2_1_X3i.root',
# 'root://eoscms//eos/cms/store/group/phys_tau/CMSSW_5_3_x/TauTriggerStudies/Ztautau_mc_v4/patTuple_3_1_In7.root',
# 'root://eoscms//eos/cms/store/group/phys_tau/CMSSW_5_3_x/TauTriggerStudies/Ztautau_mc_v4/patTuple_4_1_zCP.root',
# 'root://eoscms//eos/cms/store/group/phys_tau/CMSSW_5_3_x/TauTriggerStudies/Ztautau_mc_v4/patTuple_5_1_1Q8.root',
# 'root://eoscms//eos/cms/store/group/phys_tau/CMSSW_5_3_x/TauTriggerStudies/Ztautau_mc_v4/patTuple_6_1_wmE.root',
# 'root://eoscms//eos/cms/store/group/phys_tau/CMSSW_5_3_x/TauTriggerStudies/Ztautau_mc_v4/patTuple_7_1_wA8.root',
# 'root://eoscms//eos/cms/store/group/phys_tau/CMSSW_5_3_x/TauTriggerStudies/Ztautau_mc_v4/patTuple_8_1_PJ4.root',
# 'root://eoscms//eos/cms/store/group/phys_tau/CMSSW_5_3_x/TauTriggerStudies/Ztautau_mc_v4/patTuple_9_1_sCt.root',
# 
# 
# 'root://eoscms//eos/cms/store/group/phys_tau/CMSSW_5_3_x/TauTriggerStudies/Zprime_mc_v3/patTuple_10_1_1ZT.root',
# 'root://eoscms//eos/cms/store/group/phys_tau/CMSSW_5_3_x/TauTriggerStudies/Zprime_mc_v3/patTuple_11_1_v1d.root',
# 'root://eoscms//eos/cms/store/group/phys_tau/CMSSW_5_3_x/TauTriggerStudies/Zprime_mc_v3/patTuple_12_1_Di7.root',
# 'root://eoscms//eos/cms/store/group/phys_tau/CMSSW_5_3_x/TauTriggerStudies/Zprime_mc_v3/patTuple_13_1_3ea.root',
# 'root://eoscms//eos/cms/store/group/phys_tau/CMSSW_5_3_x/TauTriggerStudies/Zprime_mc_v3/patTuple_14_1_kj0.root',
# 'root://eoscms//eos/cms/store/group/phys_tau/CMSSW_5_3_x/TauTriggerStudies/Zprime_mc_v3/patTuple_15_1_ngP.root',
# 'root://eoscms//eos/cms/store/group/phys_tau/CMSSW_5_3_x/TauTriggerStudies/Zprime_mc_v3/patTuple_16_1_GfS.root',
# 'root://eoscms//eos/cms/store/group/phys_tau/CMSSW_5_3_x/TauTriggerStudies/Zprime_mc_v3/patTuple_17_1_iuq.root',
# 'root://eoscms//eos/cms/store/group/phys_tau/CMSSW_5_3_x/TauTriggerStudies/Zprime_mc_v3/patTuple_18_1_KzQ.root',
# 'root://eoscms//eos/cms/store/group/phys_tau/CMSSW_5_3_x/TauTriggerStudies/Zprime_mc_v3/patTuple_19_1_rNm.root',
# 'root://eoscms//eos/cms/store/group/phys_tau/CMSSW_5_3_x/TauTriggerStudies/Zprime_mc_v3/patTuple_1_1_5PH.root',
# 'root://eoscms//eos/cms/store/group/phys_tau/CMSSW_5_3_x/TauTriggerStudies/Zprime_mc_v3/patTuple_20_1_beV.root',
# 'root://eoscms//eos/cms/store/group/phys_tau/CMSSW_5_3_x/TauTriggerStudies/Zprime_mc_v3/patTuple_21_1_Nmv.root',
# 'root://eoscms//eos/cms/store/group/phys_tau/CMSSW_5_3_x/TauTriggerStudies/Zprime_mc_v3/patTuple_22_1_Z3i.root',
# 'root://eoscms//eos/cms/store/group/phys_tau/CMSSW_5_3_x/TauTriggerStudies/Zprime_mc_v3/patTuple_23_1_gVl.root',
# 'root://eoscms//eos/cms/store/group/phys_tau/CMSSW_5_3_x/TauTriggerStudies/Zprime_mc_v3/patTuple_24_1_Hqw.root',
# 'root://eoscms//eos/cms/store/group/phys_tau/CMSSW_5_3_x/TauTriggerStudies/Zprime_mc_v3/patTuple_25_1_7eQ.root',
# 'root://eoscms//eos/cms/store/group/phys_tau/CMSSW_5_3_x/TauTriggerStudies/Zprime_mc_v3/patTuple_26_1_Anl.root',
# 'root://eoscms//eos/cms/store/group/phys_tau/CMSSW_5_3_x/TauTriggerStudies/Zprime_mc_v3/patTuple_2_1_w6W.root',
# 'root://eoscms//eos/cms/store/group/phys_tau/CMSSW_5_3_x/TauTriggerStudies/Zprime_mc_v3/patTuple_3_1_UGL.root',
# 'root://eoscms//eos/cms/store/group/phys_tau/CMSSW_5_3_x/TauTriggerStudies/Zprime_mc_v3/patTuple_4_1_JMS.root',
# 'root://eoscms//eos/cms/store/group/phys_tau/CMSSW_5_3_x/TauTriggerStudies/Zprime_mc_v3/patTuple_5_1_xvX.root',
# 'root://eoscms//eos/cms/store/group/phys_tau/CMSSW_5_3_x/TauTriggerStudies/Zprime_mc_v3/patTuple_6_1_Eb2.root',
# 'root://eoscms//eos/cms/store/group/phys_tau/CMSSW_5_3_x/TauTriggerStudies/Zprime_mc_v3/patTuple_7_1_dmb.root',
# 'root://eoscms//eos/cms/store/group/phys_tau/CMSSW_5_3_x/TauTriggerStudies/Zprime_mc_v3/patTuple_8_1_9jv.root',
# 'root://eoscms//eos/cms/store/group/phys_tau/CMSSW_5_3_x/TauTriggerStudies/Zprime_mc_v3/patTuple_9_1_svY.root',
    
]        
            